controllers:
    resource: ../src/Controller/
    type: attribute

kernel:
    resource: ../src/Kernel.php
    type: annotation

index:
    path: /
    controller: App\Controller\HomeController

live_component:
    resource: '@LiveComponentBundle/Resources/config/routing/live_component.xml'